#!/usr/bin/env bash
set -euo pipefail

# create_configs.sh
# Prepares the minimal set of configured build directories used by the
# variant build workflow and writes scripts/variants.conf.
#
# The ref-proc variants share one configured build per debug level and swap
# per-variant HotSpot caches in and out of that workspace. The weak_fields
# variant keeps a dedicated configured build because it patches code outside
# HotSpot as well.
#
# Usage:
#   ./scripts/create_configs.sh

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "${SCRIPT_DIR}/variant_common.sh"

OUT_CONF_FILE="${SCRIPT_DIR}/variants.conf"
DEBUG_LEVELS=("release" "fastdebug")

ensure_patch_layout

cd "${REPO_ROOT}"

cat > "${OUT_CONF_FILE}" <<EOF
# debug_level|conf_name|variant|image_name|mode
# Auto-generated by scripts/create_configs.sh
EOF

for level in "${DEBUG_LEVELS[@]}"; do
  shared_conf="$(shared_conf_name "${level}")"
  weak_fields_conf="$(dedicated_conf_name "weak_fields" "${level}")"

  for conf_name in "${shared_conf}" "${weak_fields_conf}"; do
    echo
    echo "=== Preparing config: ${conf_name} ==="

    if [ ! -d "build/${conf_name}" ]; then
      echo "Running: bash configure --with-conf-name=${conf_name} --with-debug-level=${level}"
      bash configure --with-conf-name="${conf_name}" --with-debug-level="${level}"
    else
      echo "Skipping configure; build/${conf_name} already exists"
    fi
  done

  for variant in "${VARIANT_LIST[@]}"; do
    image_name="$(variant_image_name "${variant}" "${level}")"
    mode="shared-hotspot"
    conf_name="${shared_conf}"

    if [ "${variant}" = "weak_fields" ]; then
      mode="dedicated"
      conf_name="${weak_fields_conf}"
    fi

    printf '%s|%s|%s|%s|%s\n' \
      "${level}" \
      "${conf_name}" \
      "${variant}" \
      "${image_name}" \
      "${mode}" >> "${OUT_CONF_FILE}"
  done
done

echo
echo "Wrote mapping to ${OUT_CONF_FILE}"
echo "Run scripts/build_configs.sh to refresh variant images under build/variant-images/."
