#!/usr/bin/env bash
set -euo pipefail

# create_configs.sh
# Creates per-variant CONF directories using configure --with-conf-name
# and writes a variants mapping file at scripts/variants.conf
#
# Usage:
#   ./scripts/create_configs.sh

OUT_CONF_FILE="$(dirname "$0")/variants.conf"
MAKE_TARGET="exploded-image"
debug_levels=("release" "fastdebug")

variants=(
  "none"
  "clear_path_only"
  "sep_only"
  "dyn_only"
  "clear_path_sep"
  "clear_path_dyn"
  "sep_dyn"
  "all"
)

selected_variants=("${variants[@]}")

# Write header for mapping file
cat > "${OUT_CONF_FILE}" <<EOF
# conf_name|flags
# Auto-generated by scripts/create_configs.sh
EOF

orig_cflags="${CFLAGS:-}"
orig_cxxflags="${CXXFLAGS:-}"

for name in "${selected_variants[@]}"; do
  case "${name}" in
    none)
      clear_path_val=0; sep_val=0; dyn_val=0;;
    clear_path_only)
      clear_path_val=1; sep_val=0; dyn_val=0;;
    sep_only)
      clear_path_val=0; sep_val=1; dyn_val=0;;
    dyn_only)
      clear_path_val=0; sep_val=0; dyn_val=1;;
    clear_path_sep)
      clear_path_val=1; sep_val=1; dyn_val=0;;
    clear_path_dyn)
      clear_path_val=1; sep_val=0; dyn_val=1;;
    sep_dyn)
      clear_path_val=0; sep_val=1; dyn_val=1;;
    all)
      clear_path_val=1; sep_val=1; dyn_val=1;;
    *)
      clear_path_val=0; sep_val=0; dyn_val=0;;
  esac

  flags="-DZUseOptimisedClearPath=${clear_path_val}"
  flags+=" -DZUseSeparateDiscoveredLists=${sep_val}"
  flags+=" -DZUseDynamicArray=${dyn_val}"

  for level in "${debug_levels[@]}"; do
    conf_name="${name}-linux-x86_64-server-${level}"

    echo
    echo "=== Preparing config: ${conf_name} ==="
    echo "Flags: ${flags}"

    if [ ! -d "build/${conf_name}" ]; then
      echo "Running: bash configure --with-conf-name=${conf_name} --with-debug-level=${level}"
      bash configure --with-conf-name="${conf_name}" --with-debug-level="${level}"
    else
      echo "Skipping configure; build/${conf_name} already exists"
    fi

    # Save mapping line in variants.conf: conf_name|flags
    printf "%s|%s\n" "${conf_name}" "${flags}" >> "${OUT_CONF_FILE}"
  done

done

echo
echo "Wrote mapping to ${OUT_CONF_FILE}"

echo "Run scripts/build_configs.sh to build the prepared configurations."
