#!/usr/bin/env bash
set -euo pipefail

# create_configs.sh
# Creates per-variant CONF directories using configure --with-conf-name
# and writes a variants mapping file at scripts/variants.conf

OUT_CONF_FILE="$(dirname "$0")/variants.conf"
MAKE_TARGET="exploded-image"

variants=(
  "seq_only"
  "seq_sep"
  "sep_only"
  "sep_dyn"
  "none"
  "all"
)

# Write header for mapping file
cat > "${OUT_CONF_FILE}" <<EOF
# conf_name|flags
# Auto-generated by scripts/create_configs.sh
EOF

orig_cflags="${CFLAGS:-}"
orig_cxxflags="${CXXFLAGS:-}"

for name in "${variants[@]}"; do
  case "${name}" in
    seq_only)
      seq_val=1; sep_val=0; dyn_val=0;;
    seq_sep)
      seq_val=1; sep_val=1; dyn_val=0;;
    sep_only)
      seq_val=0; sep_val=1; dyn_val=0;;
    sep_dyn)
      seq_val=0; sep_val=1; dyn_val=1;;
    none)
      seq_val=0; sep_val=0; dyn_val=0;;
    all)
      seq_val=1; sep_val=1; dyn_val=1;;
    *)
      seq_val=0; sep_val=0; dyn_val=0;;
  esac

  flags="-DZUseSeqCodeOptimisations=${seq_val}"
  flags+=" -DZUseSeperateDiscoveredLists=${sep_val}"
  flags+=" -DZUseDynamicArray=${dyn_val}"

  conf_name="${name}-linux-x86_64-server-release"

  echo
  echo "=== Preparing config: ${conf_name} ==="
  echo "Flags: ${flags}"

  if [ ! -d "build/${conf_name}" ]; then
    echo "Running: bash configure --with-conf-name=${conf_name}"
    bash configure --with-conf-name="${conf_name}"
  else
    echo "Skipping configure; build/${conf_name} already exists"
  fi

  # Save mapping line in variants.conf: conf_name|flags
  printf "%s|%s\n" "${conf_name}" "${flags}" >> "${OUT_CONF_FILE}"

done

echo
echo "Wrote mapping to ${OUT_CONF_FILE}"

echo "Run scripts/build_configs.sh to build the prepared configurations."
